name: Tests
on: [push]
jobs:
  appleclang-macos:
    strategy:
      matrix:
        macos: [10.15, 11]
        cpp: [17, "2a"]
    name: "AppleClang (MacOS ${{ matrix.macos }}, C++${{ matrix.cpp }})"
    runs-on: macos-${{ matrix.macos }}
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=${{ matrix.cpp }}
  gcc-9-3-ubuntu-2004-cpp17:
    name: "GCC 9.3 (Ubuntu 20.04, C++17)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=17 CXXFLAGS=-DCTRE_ENABLE_LITERALS PEDANTIC=""
  gcc-ubuntu-2004-cpp20:
    strategy:
      matrix:
        gcc: [9, 10, 11]
    name: "GCC ${{ matrix.gcc }} (Ubuntu 20.04, C++20)"
    runs-on: ubuntu-20.04
    steps:
      - name: "Install GCC"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=2a
  clang-ubuntu-2004-cpp20:
    strategy:
      matrix:
        clang: [9, 10, 11, 12, 13]
    name: "Clang ${{ matrix.clang }} (Ubuntu 20.04, C++20)"
    runs-on: ubuntu-20.04
    steps:
      - name: "Install Clang"
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang }}
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=2a
