name: Tests
on: [push]
jobs:
  appleclang-macos-11-cpp17:
    name: "MacOS 11 (C++17)"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=17
  appleclang-macos-11-cpp20:
    name: "MacOS 11 (C++20)"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=20
  appleclang-macos-1015-cpp17:
    name: "MacOS 10.15 (C++17)"
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=17
  appleclang-macos-1015-cpp20:
    name: "MacOS 10.15 (C++20)"
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=2a
  gcc-ubuntu-2004-cpp17:
    name: "GCC Ubuntu 20.04 (C++17)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=17
  gcc-ubuntu-2004-cpp20:
    name: "GCC Ubuntu 20.04 (C++20)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=2a
