name: Tests
on: [push]
jobs:
  appleclang-macos-cpp17:
    strategy:
      matrix:
        macos: [10.15, 11]
    name: "AppleClang (MacOS ${{ matrix.macos }}, C++17)"
    runs-on: macos-${{ matrix.macos }}
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=17
  appleclang-macos-cpp20:
    strategy:
      matrix:
        macos: [10.15, 11]
    name: "AppleClang (MacOS ${{ matrix.macos }}, C++20)"
    runs-on: macos-${{ matrix.macos }}
    steps:
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=2a
  gcc-ubuntu-2004-cpp17:
    strategy:
      matrix:
        gcc: [9, 10, 11]
    name: "GCC ${{ matrix.gcc }} (C++17)"
    runs-on: ubuntu-20.04
    steps:
      - name: "Install GCC"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=17 CXXFLAGS=-DCTRE_ENABLE_LITERALS PEDANTIC=""
  gcc-ubuntu-2004-cpp20:
    strategy:
      matrix:
        gcc: [9, 10, 11]
    name: "GCC ${{ matrix.gcc }} (C++20)"
    runs-on: ubuntu-20.04
    steps:
      - name: "Install GCC"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=2a
  clang-ubuntu-2004-cpp17:
    strategy:
      matrix:
        clang: [9, 10, 11, 12, 13]
        stdlib: ["libc++", "libstdc++"]
    name: "Clang ${{ matrix.clang }} (C++17)"
    runs-on: ubuntu-20.04
    steps:
      - name: "Install Clang"
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang }}
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=17 CXXFLAGS=-stdlib=${{ matrix.stdlib }}
  clang-ubuntu-2004-cpp20:
    strategy:
      matrix:
        clang: [9, 10, 11, 12, 13]
        stdlib: ["libc++", "libstdc++"]
    name: "Clang ${{ matrix.clang }} (C++20)"
    runs-on: ubuntu-20.04
    steps:
      - name: "Install Clang"
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang }}
      - uses: actions/checkout@v2
      - run: c++ -v
      - run: make CXX_STANDARD=2a CXXFLAGS=-stdlib=${{ matrix.stdlib }}
